local Fmt = require("highlite.fmt") --- @type highlite.Fmt
local Nvim = require("highlite.nvim") --- @type highlite.Nvim
local Util = require("highlite.export.util") --- @type highlite.export.Util

local FMT = [[
# Generated by https://github.com/Iron-E/nvim-highlite

# Or, individual color settings can be configured or overridden.
#
# Values can be one of:
# - A color name such as "red" (see `ansi -l` for a list)
# - A color RGB value in the form of "#C4C9C6"
# - A record including:
#   * `fg` (color)
#   * `bg` (color)
#   * `attr`: a string with one or more of:
#     - 'n': normal
#     - 'b': bold
#     - 'u': underline
#     - 'r': reverse
#     - 'i': italics
#     - 'd': dimmed

export def main []: nothing -> record {
	return {
		foreground: { fg: ${}, bg: ${}, attr: "" }
		background: { fg: ${}, bg: ${}, attr: "" }
		cursor: { fg: ${}, bg: ${}, attr: "" }
		shape_string: { fg: ${}, bg: ${}, attr: "" }
		shape_string_interpolation: { fg: ${}, bg: ${}, attr: "" }
		shape_raw_string: { fg: ${}, bg: ${}, attr: "" }
		shape_record: { fg: ${}, bg: ${}, attr: "" }
		shape_list: { fg: ${}, bg: ${}, attr: "" }
		shape_table: { fg: ${}, bg: ${}, attr: "" }
		shape_bool: { fg: ${}, bg: ${}, attr: "" }
		shape_int: { fg: ${}, bg: ${}, attr: "" }
		shape_float: { fg: ${}, bg: ${}, attr: "" }
		shape_range: { fg: ${}, bg: ${}, attr: "" }
		shape_binary: { fg: ${}, bg: ${}, attr: "" }
		shape_datetime: { fg: ${}, bg: ${}, attr: "" }
		shape_custom: { fg: ${}, bg: ${}, attr: "" }
		shape_nothing: { fg: ${}, bg: ${}, attr: "" }
		shape_literal: { fg: ${}, bg: ${}, attr: "" }
		shape_operator: { fg: ${}, bg: ${}, attr: "" }
		shape_filepath: { fg: ${}, bg: ${}, attr: "" }
		shape_directory: { fg: ${}, bg: ${}, attr: "" }
		shape_globpattern: { fg: ${}, bg: ${}, attr: "" }
		shape_glob_interpolation: { fg: ${}, bg: ${}, attr: "" }
		shape_garbage: { fg: ${}, bg: ${}, attr: "" }
		shape_variable: { fg: ${}, bg: ${}, attr: "" }
		shape_vardecl: { fg: ${}, bg: ${}, attr: "" }
		shape_matching_brackets: { fg: ${}, bg: ${}, attr: "" }
		shape_pipe: { fg: ${}, bg: ${}, attr: "" }
		shape_internalcall: { fg: ${}, bg: ${}, attr: "" }
		shape_external: { fg: ${}, bg: ${}, attr: "" }
		shape_external_resolved: { fg: ${}, bg: ${}, attr: "" }
		shape_externalarg: { fg: ${}, bg: ${}, attr: "" }
		shape_match_pattern: { fg: ${}, bg: ${}, attr: "" }
		shape_block: { fg: ${}, bg: ${}, attr: "" }
		shape_signature: { fg: ${}, bg: ${}, attr: "" }
		shape_keyword: { fg: ${}, bg: ${}, attr: "" }
		shape_closure: { fg: ${}, bg: ${}, attr: "" }
		shape_redirection: { fg: ${}, bg: ${}, attr: "" }
		shape_flag: { fg: ${}, bg: ${}, attr: "" }
		bool: { fg: ${}, bg: ${}, attr: "" }
		int: { fg: ${}, bg: ${}, attr: "" }
		string: { fg: ${}, bg: ${}, attr: "" }
		float: { fg: ${}, bg: ${}, attr: "" }
		glob: { fg: ${}, bg: ${}, attr: "" }
		binary: { fg: ${}, bg: ${}, attr: "" }
		custom: { fg: ${}, bg: ${}, attr: "" }
		nothing: { fg: ${}, bg: ${}, attr: "" }
		date: { fg: ${}, bg: ${}, attr: "" }
		filesize: { fg: ${}, bg: ${}, attr: "" }
		list: { fg: ${}, bg: ${}, attr: "" }
		record: { fg: ${}, bg: ${}, attr: "" }
		duration: { fg: ${}, bg: ${}, attr: "" }
		range: { fg: ${}, bg: ${}, attr: "" }
		cell-path: { fg: ${}, bg: ${}, attr: "" }
		closure: { fg: ${}, bg: ${}, attr: "" }
		block: { fg: ${}, bg: ${}, attr: "" }
		hints: { fg: ${}, bg: ${}, attr: "" }
		search_result: { fg: ${}, bg: ${}, attr: "" }
		header: { fg: ${}, bg: ${}, attr: "" }
		separator: { fg: ${}, bg: ${}, attr: "" }
		row_index: { fg: ${}, bg: ${}, attr: "" }
		empty: { fg: ${}, bg: ${}, attr: "" }
		leading_trailing_space_bg: { fg: ${}, bg: ${}, attr: "" }
		banner_foreground: { fg: ${}, bg: ${}, attr: "" }
		banner_highlight1: { fg: ${}, bg: ${}, attr: "" }
		banner_highlight2: { fg: ${}, bg: ${}, attr: "" }
	}
}
]]

--- @type highlite.Fmt.string.opts
local FMT_OPTS = {
	default = {
		bg = "",
		blend = "",
		bold = "",
		default = "",
		fg = "",
		italic = "",
		nocombine = "",
		reverse = "",
		sp = "",
		standout = "",
		strikethrough = "",
		undercurl = "",
		underdashed = "",
		underdotted = "",
		underdouble = "",
		underline = "",
	},

	map = {
		--- @param value string
		bg = function(value)
			return value:sub(2, -2)
		end,
		blend = function()
			return "blend "
		end,
		bold = function()
			return "bold "
		end,
		default = function()
			return "default "
		end,
		italic = function()
			return "italic "
		end,
		nocombine = function()
			return "nocombine "
		end,
		reverse = function()
			return "reverse "
		end,
		standout = function()
			return "standout "
		end,
		strikethrough = function()
			return "squiggly_underline "
		end, --- NOTE: Sublime Text does not support strikethrough
		undercurl = function()
			return "squiggly_underline "
		end,
		underdouble = function()
			return "stippled_underline "
		end,
		underline = function()
			return "underline "
		end,
	},
}

FMT_OPTS.map.fg = FMT_OPTS.map.bg
FMT_OPTS.map.sp = FMT_OPTS.map.bg

FMT_OPTS.map.underdotted = FMT_OPTS.map.underline
FMT_OPTS.map.underdotted = FMT_OPTS.map.underline

--- Create a wezterm theme out of the `palette`
--- @type highlite.export.format.module
local function export(colorscheme, opts, dir)
	if opts == nil then
		opts = {}
	end

	-- checked for backwards compatability
	dir = Util.get_normalized_dir("nushell", dir or opts.dir, function()
		local nu_config_dir = vim.fn.system({ "nu", "-c", "$NU_LIB_DIRS | first" }):sub(1, -2)
		return nu_config_dir .. "/themes/"
	end)

	local filename = opts.filename or colorscheme

	local content --- @type string
	Nvim.with_colorscheme(colorscheme, function()
		content = Fmt.string(FMT, FMT_OPTS)
	end)

	return dir .. "/" .. filename .. ".nu", content, opts
end

return export
