local Fmt = require 'highlite.fmt' --- @type highlite.Fmt
local Nvim = require 'highlite.nvim' --- @type highlite.Nvim
local Util = require 'highlite.export.util' --- @type highlite.export.Util

-- TODO: tailspin formatting
local FMT = [=[
[dates]
date = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
time = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
zone = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[[keywords]]
words = ['null', 'true', 'false']
style = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[[keywords]]
words = ['GET']
style = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[urls]
http = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
https = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
host = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
path = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
query_params_key = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
query_params_value = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
symbols = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[numbers]
style = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[ip_addresses]
number = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
letter = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[quotes]
style = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
token = '"'

[paths]
segment = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[uuids]
number = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
letter = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[pointers]
number = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
letter = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[key_value_pairs]
key = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[processes]
name = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
separator = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
id = { fg = "color", bg = "color", italic = false, bold = false, underline = false }

[json]
key = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
quote_token = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
curly_bracket = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
square_bracket = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
comma = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
colon = { fg = "color", bg = "color", italic = false, bold = false, underline = false }
]=]

--- @type highlite.Fmt.string.opts
local FMT_OPTS =
{
}

--- Create a wezterm theme out of the `palette`
--- @type highlite.export.format.module
local function export(colorscheme, opts, dir)
	-- TODO: tailspin logic
	if opts == nil then opts = {} end

	-- checked for backwards compatability
	dir = Util.get_normalized_dir('bat', dir or opts.dir, function ()
		local bat_config_dir = vim.fn.system({'bat', '--config-dir'}):sub(1, -2)
		return bat_config_dir .. '/themes'
	end)

	local filename = opts.filename or colorscheme

	local content --- @type string
	Nvim.with_colorscheme(colorscheme, function()
		content = [[<!-- Generated by https://github.com/Iron-E/nvim-highlite -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>]] .. filename .. [[</string>]] .. Fmt.string(FMT, FMT_OPTS):gsub('\n(%s+)<key>%w+</key>%s+<string></string>', '')
	end)

	return dir .. '/' .. filename .. '.tmTheme', content, opts
end

return export
