local Fmt = require 'highlite.fmt' --- @type highlite.Fmt
local Nvim = require 'highlite.nvim' --- @type highlite.Nvim
local Util = require 'highlite.export.util' --- @type highlite.export.Util

-- TODO: tailspin formatting
local FMT = [=[
# Generated by https://github.com/Iron-E/nvim-highlite

[dates]
date = {
	fg = ${@string.special.fg},
	bg = ${@string.special.bg},
	italic = ${@string.special.italic},
	bold = ${@string.special.bold},
	underline = ${@string.special.underline | @string.special.undercurl | @string.special.underdashed | @string.special.underdotted | @string.special.underdouble},
}

time = {
	fg = ${@string.special.fg},
	bg = ${@string.special.bg},
	italic = ${@string.special.italic},
	bold = ${@string.special.bold},
	underline = ${@string.special.underline | @string.special.undercurl | @string.special.underdashed | @string.special.underdotted | @string.special.underdouble},
}

# zone = {
# 	fg = "color",
# 	bg = "color",
# 	italic = false,
# 	bold = false,
# 	underline = false,
# }

separator = {
	fg = ${@punctuation.delimiter.fg},
	bg = ${@punctuation.delimiter.bg},
	italic = ${@punctuation.delimiter.italic},
	bold = ${@punctuation.delimiter.bold},
	underline = ${@punctuation.delimiter.underline | @punctuation.delimiter.undercurl | @punctuation.delimiter.underdashed | @punctuation.delimiter.underdotted | @punctuation.delimiter.underdouble},
}

[[keywords]]
words = ['true', 'false']
style = {
	fg = ${@boolean.fg | Boolean.fg},
	bg = ${@boolean.bg | Boolean.bg},
	italic = ${@boolean.italic | Boolean.italic},
	bold = ${@boolean.bold | Boolean.bold},
	underline = ${@boolean.undercurl | @boolean.underdashed | @boolean.underdotted | @boolean.underdouble | @boolean.underline | Boolean.undercurl | Boolean.underdashed | Boolean.underdotted | Boolean.underdouble | Boolean.underline},
}

[[keywords]]
words = ['null']
style = {
	fg = ${@constant.builtin.fg},
	bg = ${@constant.builtin.bg},
	italic = ${@constant.builtin.italic},
	bold = ${@constant.builtin.bold},
	underline = ${@constant.builtin.underline | @constant.builtin.undercurl | @constant.builtin.underdashed | @constant.builtin.underdotted | @constant.builtin.underdouble},
}

# [[keywords]]
# words = ['GET']
# style = {
# 	fg = ${foo.fg},
# 	bg = ${foo.bg},
# 	italic = ${foo.italic},
# 	bold = ${foo.bold},
# 	underline = ${foo.underline | foo.undercurl | foo.underdashed | foo.underdotted | foo.underdouble},
# }

[urls]
http = {
	fg = ${@string.special.url.fg | Underline.fg},
	bg = ${@string.special.url.bg | Underline.bg},
	italic = ${@string.special.url.italic | Underline.italic},
	bold = ${@string.special.url.bold | Underline.bold},
	underline = ${@string.special.url.undercurl | @string.special.url.underdashed | @string.special.url.underdotted | @string.special.url.underdouble | @string.special.url.underline | Underline.undercurl | Underline.underdashed | Underline.underdotted | Underline.underdouble | Underline.underline},
}

https = {
	fg = ${@string.special.url.fg | Underline.fg},
	bg = ${@string.special.url.bg | Underline.bg},
	italic = ${@string.special.url.italic | Underline.italic},
	bold = ${@string.special.url.bold | Underline.bold},
	underline = ${@string.special.url.undercurl | @string.special.url.underdashed | @string.special.url.underdotted | @string.special.url.underdouble | @string.special.url.underline | Underline.undercurl | Underline.underdashed | Underline.underdotted | Underline.underdouble | Underline.underline},
}

host = {
	fg = ${@string.special.url.fg | Underline.fg},
	bg = ${@string.special.url.bg | Underline.bg},
	italic = ${@string.special.url.italic | Underline.italic},
	bold = ${@string.special.url.bold | Underline.bold},
	underline = ${@string.special.url.undercurl | @string.special.url.underdashed | @string.special.url.underdotted | @string.special.url.underdouble | @string.special.url.underline | Underline.undercurl | Underline.underdashed | Underline.underdotted | Underline.underdouble | Underline.underline},
}

path = {
	fg = ${@string.special.url.fg | Underline.fg},
	bg = ${@string.special.url.bg | Underline.bg},
	italic = ${@string.special.url.italic | Underline.italic},
	bold = ${@string.special.url.bold | Underline.bold},
	underline = ${@string.special.url.undercurl | @string.special.url.underdashed | @string.special.url.underdotted | @string.special.url.underdouble | @string.special.url.underline | Underline.undercurl | Underline.underdashed | Underline.underdotted | Underline.underdouble | Underline.underline},
}

query_params_key = {
	fg = ${@property.fg},
	bg = ${@property.bg},
	italic = ${@property.italic},
	bold = ${@property.bold},
	underline = ${@property.underline | @property.undercurl | @property.underdashed | @property.underdotted | @property.underdouble},
}

query_params_value = {
	fg = ${@string.fg},
	bg = ${@string.bg},
	italic = ${@string.italic},
	bold = ${@string.bold},
	underline = ${@string.underline | @string.undercurl | @string.underdashed | @string.underdotted | @string.underdouble},
}

symbols = {
	fg = ${@string.special.symbol.fg},
	bg = ${@string.special.symbol.bg},
	italic = ${@string.special.symbol.italic},
	bold = ${@string.special.symbol.bold},
	underline = ${@string.special.symbol.underline | foo.undercurl | foo.underdashed | foo.underdotted | foo.underdouble},
}

[numbers]
style = {
	fg = ${@number.fg},
	bg = ${@number.bg},
	italic = ${@number.italic},
	bold = ${@number.bold},
	underline = ${@number.underline | @number.undercurl | @number.underdashed | @number.underdotted | @number.underdouble},
}

[ip_addresses]
number = {
	fg = ${@string.special.fg},
	bg = ${@string.special.bg},
	italic = ${@string.special.italic},
	bold = ${@string.special.bold},
	underline = ${@string.special.underline | @string.special.undercurl | @string.special.underdashed | @string.special.underdotted | @string.special.underdouble},
}

letter = {
	fg = ${@string.special.fg},
	bg = ${@string.special.bg},
	italic = ${@string.special.italic},
	bold = ${@string.special.bold},
	underline = ${@string.special.underline | @string.special.undercurl | @string.special.underdashed | @string.special.underdotted | @string.special.underdouble},
}

separator = {
	fg = ${@puncutation.delimiter.fg},
	bg = ${@puncutation.delimiter.bg},
	italic = ${@puncutation.delimiter.italic},
	bold = ${@puncutation.delimiter.bold},
	underline = ${@puncutation.delimiter.underline | foo.undercurl | foo.underdashed | foo.underdotted | foo.underdouble},
}

[quotes]
token = '"'
style = {
	fg = ${@conceal.fg},
	bg = ${@conceal.bg},
	italic = ${@conceal.italic},
	bold = ${@conceal.bold},
	underline = ${@conceal.underline | @conceal.undercurl | @conceal.underdashed | @conceal.underdotted | @conceal.underdouble},
}

[paths]
segment = {
	fg = ${@string.special.path.fg},
	bg = ${@string.special.path.bg},
	italic = ${@string.special.path.italic},
	bold = ${@string.special.path.bold},
	underline = ${@string.special.path.underline | @string.special.path.undercurl | @string.special.path.underdashed | @string.special.path.underdotted | @string.special.path.underdouble},
}

separator = {
	fg = ${@punctuation.delimiter.fg},
	bg = ${@punctuation.delimiter.bg},
	italic = ${@punctuation.delimiter.italic},
	bold = ${@punctuation.delimiter.bold},
	underline = ${@punctuation.delimiter.underline | @punctuation.delimiter.undercurl | @punctuation.delimiter.underdashed | @punctuation.delimiter.underdotted | @punctuation.delimiter.underdouble},
}


[uuids]
number = {
	fg = ${@string.special.fg},
	bg = ${@string.special.bg},
	italic = ${@string.special.italic},
	bold = ${@string.special.bold},
	underline = ${@string.special.underline | @string.special.undercurl | @string.special.underdashed | @string.special.underdotted | @string.special.underdouble},
}

letter = {
	fg = ${@string.special.fg},
	bg = ${@string.special.bg},
	italic = ${@string.special.italic},
	bold = ${@string.special.bold},
	underline = ${@string.special.underline | @string.special.undercurl | @string.special.underdashed | @string.special.underdotted | @string.special.underdouble},
}

separator = {
	fg = ${@punctuation.delimiter.fg},
	bg = ${@punctuation.delimiter.bg},
	italic = ${@punctuation.delimiter.italic},
	bold = ${@punctuation.delimiter.bold},
	underline = ${@punctuation.delimiter.underline | @punctuation.delimiter.undercurl | @punctuation.delimiter.underdashed | @punctuation.delimiter.underdotted | @punctuation.delimiter.underdouble},
}

[pointers]
number = {
	fg = ${@number.fg},
	bg = ${@number.bg},
	italic = ${@number.italic},
	bold = ${@number.bold},
	underline = ${@number.underline | @number.undercurl | @number.underdashed | @number.underdotted | @number.underdouble},
}

letter = {
	fg = ${@number.fg},
	bg = ${@number.bg},
	italic = ${@number.italic},
	bold = ${@number.bold},
	underline = ${@number.underline | @number.undercurl | @number.underdashed | @number.underdotted | @number.underdouble},
}

separator = {
	fg = ${@punctuation.delimiter.fg},
	bg = ${@punctuation.delimiter.bg},
	italic = ${@punctuation.delimiter.italic},
	bold = ${@punctuation.delimiter.bold},
	underline = ${@punctuation.delimiter.underline | @punctuation.delimiter.undercurl | @punctuation.delimiter.underdashed | @punctuation.delimiter.underdotted | @punctuation.delimiter.underdouble},
}

[key_value_pairs]
key = {
	fg = ${foo.fg},
	bg = ${foo.bg},
	italic = ${foo.italic},
	bold = ${foo.bold},
	underline = ${foo.underline | foo.undercurl | foo.underdashed | foo.underdotted | foo.underdouble},
}

separator = {
	fg = ${foo.fg},
	bg = ${foo.bg},
	italic = ${foo.italic},
	bold = ${foo.bold},
	underline = ${foo.underline | foo.undercurl | foo.underdashed | foo.underdotted | foo.underdouble},
}

[processes]
name = {
	fg = ${@module.fg},
	bg = ${@module.bg},
	italic = ${@module.italic},
	bold = ${@module.bold},
	underline = ${@module.underline | @module.undercurl | @module.underdashed | @module.underdotted | @module.underdouble},
}

separator = {
	fg = ${@punctuation.bracket.fg},
	bg = ${@punctuation.bracket.bg},
	italic = ${@punctuation.bracket.italic},
	bold = ${@punctuation.bracket.bold},
	underline = ${@punctuation.bracket.underline | @punctuation.bracket.undercurl | @punctuation.bracket.underdashed | @punctuation.bracket.underdotted | @punctuation.bracket.underdouble},
}

id = {
	fg = ${@number.fg},
	bg = ${@number.bg},
	italic = ${@number.italic},
	bold = ${@number.bold},
	underline = ${@number.underline | @number.undercurl | @number.underdashed | @number.underdotted | @number.underdouble},
}

[json]
key = {
	fg = ${@property.fg},
	bg = ${@property.bg},
	italic = ${@property.italic},
	bold = ${@property.bold},
	underline = ${@property.underline | @property.undercurl | @property.underdashed | @property.underdotted | @property.underdouble},
}

quote_token = {
	fg = ${@conceal.fg},
	bg = ${@conceal.bg},
	italic = ${@conceal.italic},
	bold = ${@conceal.bold},
	underline = ${@conceal.underline | @conceal.undercurl | @conceal.underdashed | @conceal.underdotted | @conceal.underdouble},
}

curly_bracket = {
	fg = ${@punctuation.bracket.fg},
	bg = ${@punctuation.bracket.bg},
	italic = ${@punctuation.bracket.italic},
	bold = ${@punctuation.bracket.bold},
	underline = ${@punctuation.bracket.underline | @punctuation.bracket.undercurl | @punctuation.bracket.underdashed | @punctuation.bracket.underdotted | @punctuation.bracket.underdouble},
}

square_bracket = {
	fg = ${foo.fg},
	bg = ${foo.bg},
	italic = ${foo.italic},
	bold = ${foo.bold},
	underline = ${foo.underline | foo.undercurl | foo.underdashed | foo.underdotted | foo.underdouble},
}

comma = {
	fg = ${@punctuation.delimiter.fg},
	bg = ${@punctuation.delimiter.bg},
	italic = ${@punctuation.delimiter.italic},
	bold = ${@punctuation.delimiter.bold},
	underline = ${@punctuation.delimiter.underline | @punctuation.delimiter.undercurl | @punctuation.delimiter.underdashed | @punctuation.delimiter.underdotted | @punctuation.delimiter.underdouble},
}

colon = {
	fg = ${@punctuation.delimiter.fg},
	bg = ${@punctuation.delimiter.bg},
	italic = ${@punctuation.delimiter.italic},
	bold = ${@punctuation.delimiter.bold},
	underline = ${@punctuation.delimiter.underline | @punctuation.delimiter.undercurl | @punctuation.delimiter.underdashed | @punctuation.delimiter.underdotted | @punctuation.delimiter.underdouble},
}
]=]

--- @type highlite.Fmt.string.opts
local FMT_OPTS =
{
}

--- Create a wezterm theme out of the `palette`
--- @type highlite.export.format.module
local function export(colorscheme, opts, dir)
	-- TODO: tailspin logic
	if opts == nil then opts = {} end

	-- checked for backwards compatability
	dir = Util.get_normalized_dir('bat', dir or opts.dir, function ()
		local config_dir = vim.loop.os_getenv('XDG_CONFIG_HOME')
		return config_dir .. '/tailspin'
	end)

	local filename = opts.filename or 'theme'

	local content --- @type string
	Nvim.with_colorscheme(colorscheme, function()
		content = Fmt.string(FMT, FMT_OPTS)
	end)

	return dir .. '/' .. filename .. '.toml', content, opts
end

return export
